#!/bin/bash

case "$(uname -s)" in

   Darwin)
      node ../Fish/Common/old/compiled/compiledM4.js
     ;;

   Linux)
     /opt/rh/rh-nodejs10/root/usr/bin/node ././Fish/Common/old/compiled/compiledM4.js
     ;;

   *)

esac