#!/bin/bash

#
# USAGE: Call this script from within the ./Fish/Other directory.
# like ./tree-push
#
# PURPOSE: Generates a README.md with the tree structure of 
# Fish/ directory and commit and push README.md onto remote.
#

echo ------------------------  START OF SCRIPT  ----------------------------

currdir=${PWD##*/}

echo ---\> The current directory should be Other
echo ---\> The current directory is ${currdir}

if [ ${currdir} = "Other" ]; then
    cd visualizations
    subdir=${PWD##*/}

    echo ---\> The sub-directory of Other should be visualizations
    echo ---\> The sub-directory of Other is $subdir

    if [ ${subdir} = "visualizations" ]; then
        cd board-examples
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o board-examples.svg board-examples.drawio 
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o board-examples.png board-examples.drawio 
        cd ..
        cd board-to-matrix-construction
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o board-to-matrix-construction.svg board-to-matrix-construction.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o board-to-matrix-construction.png board-to-matrix-construction.drawio
        cd ..
        cd game-tree-visualization
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o game-tree-visualization.svg game-tree-visualization.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o game-tree-visualization.png game-tree-visualization.drawio
        cd ..
        cd referee-game-ai-separation
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o referee-game-ai-separation.svg referee-game-ai-separation.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o referee-game-ai-separation.png referee-game-ai-separation.drawio
        cd ..
        cd rough-software-architecture
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o rough-software-architecture.svg rough-software-architecture.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o rough-software-architecture.png rough-software-architecture.drawio
        cd ..
        cd tile-increase-size-flowchart
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o tile-increase-size-flowchart.svg tile-increase-size-flowchart.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o tile-increase-size-flowchart.png tile-increase-size-flowchart.drawio
        cd ..
        cd tile-size-flowchart
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o tile-size-flowchart.svg tile-size-flowchart.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o tile-size-flowchart.png tile-size-flowchart.drawio
        cd ..
        cd webpack-bundler
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o webpack-bundler.svg webpack-bundler.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o webpack-bundler.png webpack-bundler.drawio
        cd ..
        cd tree-2-minimax
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f svg -o tree-2-minimax.svg tree-2-minimax.drawio
        /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o tree-2-minimax.png tree-2-minimax.drawio
        cd ..
    else
      echo ---\> !! Make sure visualizations sub-directory is present !!
    fi
else
  echo ---\> !! Call this script the Other directory !!
fi

echo ------------------------  END OF SCRIPT  ------------------------------









