#!/bin/bash

case "$(uname -s)" in

   Darwin)
      node ./Common/compiled/compiled.js
     ;;

   Linux)
     /opt/rh/rh-nodejs10/root/usr/bin/node ./Common/compiled/compiled.js
     ;;

   *)

esac