#!/bin/bash

case "$(uname -s)" in

   Darwin)
      ./xstrategy < ./1-in.json | diff - ./1-out.json;
      ./xstrategy < ./2-in.json | diff - ./2-out.json;
      ./xstrategy < ./3-in.json | diff - ./3-out.json;
      ./xstrategy < ./4-in.json | diff - ./4-out.json;
      ./xstrategy < ./5-in.json | diff - ./5-out.json;
     ;;

   Linux)
     ./xstrategy < ./1-in.json | diff - ./1-out.json
     ./xstrategy < ./2-in.json | diff - ./2-out.json
     ./xstrategy < ./3-in.json | diff - ./3-out.json
     ./xstrategy < ./4-in.json | diff - ./4-out.json
     ./xstrategy < ./5-in.json | diff - ./5-out.json
     ;;

   *)

esac
