#!/bin/bash

case "$(uname -s)" in

   Darwin)
      echo "---------- 1 ----------"
      node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./1-in.json | diff - ./1-out.json;
      echo "---------- 2 ----------"
      node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./2-in.json | diff - ./2-out.json;
      echo "---------- 3 ----------"
      node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./3-in.json | diff - ./3-out.json;
      echo "---------- 4 ----------"
      node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./4-in.json | diff - ./4-out.json;
      echo "---------- 5 ----------"
      node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./5-in.json | diff - ./5-out.json;
     ;;

   Linux)
     echo "---------- 1 ----------"
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./1-in.json | diff - ./1-out.json
     echo "---------- 2 ----------"
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./2-in.json | diff - ./2-out.json
     echo "---------- 3 ----------"
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./3-in.json | diff - ./3-out.json
     echo "---------- 4 ----------"
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./4-in.json | diff - ./4-out.json
     echo "---------- 5 ----------"
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/dist/executables/xStrategy/xStrategy.js < ./5-in.json | diff - ./5-out.json
     ;;

   *)

esac
