import { CState, CBoard, CScore } from "./cstate";
export declare const noholesboard: CBoard;
export declare const playerscores: CScore[];
export declare const placingstate: CState;
export declare const noholesboardplaced: CBoard;
export declare const placedstate: CState;
export declare const holesboard: CBoard;
export declare const threeplayerscores: CScore[];
export declare const holesplacingstate: CState;
export declare const holesboardplaced: CBoard;
export declare const holesplacedstate: CState;
export declare const holesboard2: CBoard;
export declare const holesboardplaced2: CBoard;
export declare const holesplacingstate2: CState;
export declare const holesplacedstate2: CState;
