#!/bin/bash

case "$(uname -s)" in

   Darwin)
      node ../Fish/Common/test-harness/5-test-harness.js
     ;;

   Linux)
     /opt/rh/rh-nodejs10/root/usr/bin/node ../Fish/Common/test-harness/5-test-harness.js
     ;;

   *)

esac

